import 'package:flutter/material.dart';

/// Theme catalog for Jigsaw — "Bibliophile Puzzle Sanctuary".
///
/// Every theme stays inside the cozy-library material world (real woods,
/// linen/baize mats, brass/copper/silver, parchment, warm lamplight) —
/// no neon, no cyberpunk. The variety comes from different table woods,
/// mat linings, lighting tints and cardboard piece-back tones.
class LibraryThemeDef {
  final String id;
  final String name;
  final Color woodDark; // table surface, deep tone
  final Color woodMid; // table surface, lit tone
  final Color woodDeep; // occlusion / deepest shadow
  final Color accent; // brass / copper / silver
  final Color accentLight;
  final Color accentDark;
  final Color ivory; // parchment text
  final Color ink; // espresso ink on parchment
  final Color mat; // linen puzzle mat
  final Color matDark; // mat groove / shadow
  final Color lampGlow; // warm lighting tint
  final Color pieceBack; // cardboard piece back tone
  final Color folio; // clothbound box spine accent (menu)

  const LibraryThemeDef({
    required this.id,
    required this.name,
    required this.woodDark,
    required this.woodMid,
    required this.woodDeep,
    required this.accent,
    required this.accentLight,
    required this.accentDark,
    required this.ivory,
    required this.ink,
    required this.mat,
    required this.matDark,
    required this.lampGlow,
    required this.pieceBack,
    required this.folio,
  });
}

class LibraryThemes {
  /// First 4 are the FREE starter themes. The rest are PRO.
  static const List<String> freeThemeIds = [
    'bibliophile',
    'mahogany',
    'oakmorning',
    'candlelit',
  ];

  static bool isProTheme(String id) => !freeThemeIds.contains(id);

  static const List<LibraryThemeDef> all = [
    LibraryThemeDef(
      id: 'bibliophile',
      name: 'Bibliophile Classic',
      woodDark: Color(0xFF3B2A1E),
      woodMid: Color(0xFF5A4330),
      woodDeep: Color(0xFF0C0806),
      accent: Color(0xFFC9A227),
      accentLight: Color(0xFFE8C96A),
      accentDark: Color(0xFF8A6D1A),
      ivory: Color(0xFFF3E8CB),
      ink: Color(0xFF2B1D12),
      mat: Color(0xFF2F5D43),
      matDark: Color(0xFF1C3A2A),
      lampGlow: Color(0xFFE8A94E),
      pieceBack: Color(0xFFB99B6E),
      folio: Color(0xFF3E5C43),
    ),
    LibraryThemeDef(
      id: 'mahogany',
      name: 'Royal Mahogany',
      woodDark: Color(0xFF4A1F14),
      woodMid: Color(0xFF6E3220),
      woodDeep: Color(0xFF220D06),
      accent: Color(0xFFD4AF37),
      accentLight: Color(0xFFF3DC8E),
      accentDark: Color(0xFF96702A),
      ivory: Color(0xFFF8F1E2),
      ink: Color(0xFF33160C),
      mat: Color(0xFF3D1F2E),
      matDark: Color(0xFF27121D),
      lampGlow: Color(0xFFE8A94E),
      pieceBack: Color(0xFFC49A6C),
      folio: Color(0xFF6E2A30),
    ),
    LibraryThemeDef(
      id: 'oakmorning',
      name: 'Honey Oak Morning',
      woodDark: Color(0xFF7A5230),
      woodMid: Color(0xFF9C7040),
      woodDeep: Color(0xFF3A2410),
      accent: Color(0xFFC9A227),
      accentLight: Color(0xFFEFD98F),
      accentDark: Color(0xFF8A6D1A),
      ivory: Color(0xFFF9F3E0),
      ink: Color(0xFF3A2A14),
      mat: Color(0xFF4A6B52),
      matDark: Color(0xFF2E4534),
      lampGlow: Color(0xFFF0C060),
      pieceBack: Color(0xFFD4B183),
      folio: Color(0xFFC88A2E),
    ),
    LibraryThemeDef(
      id: 'candlelit',
      name: 'Candlelit Midnight',
      woodDark: Color(0xFF232B3A),
      woodMid: Color(0xFF36415A),
      woodDeep: Color(0xFF0A0D16),
      accent: Color(0xFFC0C6D4),
      accentLight: Color(0xFFE8ECF5),
      accentDark: Color(0xFF7E8698),
      ivory: Color(0xFFF2EEE4),
      ink: Color(0xFF1A2030),
      mat: Color(0xFF1B2A4A),
      matDark: Color(0xFF0F1830),
      lampGlow: Color(0xFFE8C07A),
      pieceBack: Color(0xFF9A8E7A),
      folio: Color(0xFF232B3A),
    ),
    LibraryThemeDef(
      id: 'forestroom',
      name: 'Forest Reading Room',
      woodDark: Color(0xFF2E3B22),
      woodMid: Color(0xFF4A5A34),
      woodDeep: Color(0xFF111709),
      accent: Color(0xFFB08D3E),
      accentLight: Color(0xFFD9BC72),
      accentDark: Color(0xFF7A5F24),
      ivory: Color(0xFFF3EBD2),
      ink: Color(0xFF232B16),
      mat: Color(0xFF3F5A3A),
      matDark: Color(0xFF273A24),
      lampGlow: Color(0xFFE8B95E),
      pieceBack: Color(0xFFB69A6B),
      folio: Color(0xFF2E5A32),
    ),
    LibraryThemeDef(
      id: 'athenaeum',
      name: 'Burgundy Athenaeum',
      woodDark: Color(0xFF3A1E24),
      woodMid: Color(0xFF5A2E38),
      woodDeep: Color(0xFF180A0E),
      accent: Color(0xFFC9A227),
      accentLight: Color(0xFFE8C96A),
      accentDark: Color(0xFF8A6D1A),
      ivory: Color(0xFFF5E9D2),
      ink: Color(0xFF2E1418),
      mat: Color(0xFF5E2E36),
      matDark: Color(0xFF3C1C23),
      lampGlow: Color(0xFFE8A94E),
      pieceBack: Color(0xFFBE9A72),
      folio: Color(0xFF7A2430),
    ),
    LibraryThemeDef(
      id: 'navigator',
      name: 'Navy Navigator',
      woodDark: Color(0xFF1E2A3A),
      woodMid: Color(0xFF32455E),
      woodDeep: Color(0xFF0A0F18),
      accent: Color(0xFFB98A3E),
      accentLight: Color(0xFFE0B96A),
      accentDark: Color(0xFF7A5A24),
      ivory: Color(0xFFEFE8D2),
      ink: Color(0xFF16202E),
      mat: Color(0xFF24405A),
      matDark: Color(0xFF152A3E),
      lampGlow: Color(0xFFE8C07A),
      pieceBack: Color(0xFFA08E72),
      folio: Color(0xFF1E3A5A),
    ),
    LibraryThemeDef(
      id: 'copperhouse',
      name: 'Copper Conservatory',
      woodDark: Color(0xFF3A2418),
      woodMid: Color(0xFF5E3C26),
      woodDeep: Color(0xFF140A05),
      accent: Color(0xFFB87333),
      accentLight: Color(0xFFE09A5E),
      accentDark: Color(0xFF7A4A1E),
      ivory: Color(0xFFF6ECd4),
      ink: Color(0xFF2E1C10),
      mat: Color(0xFF4A5A2E),
      matDark: Color(0xFF2E3A1C),
      lampGlow: Color(0xFFF0B95E),
      pieceBack: Color(0xFFC49A6C),
      folio: Color(0xFF8A5A24),
    ),
    LibraryThemeDef(
      id: 'greenhouse',
      name: 'Sage Greenhouse',
      woodDark: Color(0xFF4A4234),
      woodMid: Color(0xFF6E6450),
      woodDeep: Color(0xFF201B12),
      accent: Color(0xFF9AA83E),
      accentLight: Color(0xFFC4D46A),
      accentDark: Color(0xFF6A7424),
      ivory: Color(0xFFF4EEDC),
      ink: Color(0xFF2E2A1C),
      mat: Color(0xFF6B7A4A),
      matDark: Color(0xFF45502E),
      lampGlow: Color(0xFFEED27A),
      pieceBack: Color(0xFFC2AC80),
      folio: Color(0xFF5A6E32),
    ),
    LibraryThemeDef(
      id: 'archive',
      name: 'Charcoal Archive',
      woodDark: Color(0xFF2A2A2E),
      woodMid: Color(0xFF44444A),
      woodDeep: Color(0xFF0C0C0E),
      accent: Color(0xFFB8B0A0),
      accentLight: Color(0xFFE0D8C8),
      accentDark: Color(0xFF7A7468),
      ivory: Color(0xFFF0EAE0),
      ink: Color(0xFF1E1E20),
      mat: Color(0xFF3E3E44),
      matDark: Color(0xFF26262A),
      lampGlow: Color(0xFFD8C89A),
      pieceBack: Color(0xFF9A9284),
      folio: Color(0xFF4A4A52),
    ),
    LibraryThemeDef(
      id: 'salon',
      name: 'Rosewood Salon',
      woodDark: Color(0xFF3E1F1C),
      woodMid: Color(0xFF62322C),
      woodDeep: Color(0xFF180B09),
      accent: Color(0xFFD4AF37),
      accentLight: Color(0xFFF3DC8E),
      accentDark: Color(0xFF96702A),
      ivory: Color(0xFFF8EEDC),
      ink: Color(0xFF301512),
      mat: Color(0xFF6E3A34),
      matDark: Color(0xFF462420),
      lampGlow: Color(0xFFF0B060),
      pieceBack: Color(0xFFC89A70),
      folio: Color(0xFF8A2E2A),
    ),
    LibraryThemeDef(
      id: 'cloister',
      name: 'Sandstone Cloister',
      woodDark: Color(0xFF6E5A40),
      woodMid: Color(0xFF94805E),
      woodDeep: Color(0xFF322818),
      accent: Color(0xFF8A6D3E),
      accentLight: Color(0xFFC4A86A),
      accentDark: Color(0xFF5A4A24),
      ivory: Color(0xFFFAF4E4),
      ink: Color(0xFF3A2E1C),
      mat: Color(0xFF7A6A4A),
      matDark: Color(0xFF4E4430),
      lampGlow: Color(0xFFF5D98A),
      pieceBack: Color(0xFFD4BE92),
      folio: Color(0xFFA8842E),
    ),
    LibraryThemeDef(
      id: 'cartographer',
      name: 'Teal Cartography',
      woodDark: Color(0xFF1E3230),
      woodMid: Color(0xFF34504C),
      woodDeep: Color(0xFF0A1413),
      accent: Color(0xFFC9A227),
      accentLight: Color(0xFFE8C96A),
      accentDark: Color(0xFF8A6D1A),
      ivory: Color(0xFFF0EAD6),
      ink: Color(0xFF14201E),
      mat: Color(0xFF2E5A56),
      matDark: Color(0xFF1C3A38),
      lampGlow: Color(0xFFE8C97A),
      pieceBack: Color(0xFFAC9C78),
      folio: Color(0xFF2E6A62),
    ),
    LibraryThemeDef(
      id: 'plumpress',
      name: 'Plum Press',
      woodDark: Color(0xFF33202E),
      woodMid: Color(0xFF52344C),
      woodDeep: Color(0xFF140C12),
      accent: Color(0xFFC98A3E),
      accentLight: Color(0xFFE8B96A),
      accentDark: Color(0xFF8A5A24),
      ivory: Color(0xFFF6EAD8),
      ink: Color(0xFF281820),
      mat: Color(0xFF5A3A54),
      matDark: Color(0xFF382236),
      lampGlow: Color(0xFFE8B060),
      pieceBack: Color(0xFFB8946E),
      folio: Color(0xFF6E2E62),
    ),
  ];

  static LibraryThemeDef byId(String id, {LibraryThemeDef? custom}) {
    if (id == 'custom' && custom != null) return custom;
    for (final t in all) {
      if (t.id == id) return t;
    }
    return all.first;
  }
}
